config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount GraphiQL::Rails::Engine, at: '/graphiql', graphql_path: '/graphql'

  post '/graphql', to: 'graphql#execute'

  namespace :admin do
    resources :users
    resources :zones
    resources :locations
    resources :monsters
    resources :items
    resources :npcs
    resources :quests
    resources :quest_objectives
    resources :quest_rewards
    resources :resources
    resources :images

    root to: 'zones#index'
  end

  post '/items/:item_id/image', controller: 'images', action: 'create'
  post '/monsters/:monster_id/image', controller: 'images', action: 'create'
  post '/npcs/:npc_id/image', controller: 'images', action: 'create'
  resources :images, only: %i[show]

  resources :maps, only: %i[show] # elm

  resources :monsters, only: %i[index show new edit create update]

  resources :items, only: %i[index show new edit create update] do
    get 'search', on: :collection
    get 'dynamic_stats', on: :collection
  end

  resources :locations, only: [] do
    get 'select_for_category', on: :collection, to: 'locations#select_for_category'
  end

  # get '/test', to: 'test#index'

  get '/login', to: 'users#login'
  post '/logout', to: 'users#logout'
  get '/oauth2/callback', to: 'users#oauth2_callback'

  # root to: proc { [404, {}, ['Not found.']] }
  root to: redirect('/maps/1')
end

app/models/item.rb
# frozen_string_literal: true

class Item < ApplicationRecord
  include Discard::Model
  default_scope -> { kept }

  has_paper_trail

  belongs_to :patch
  before_validation { self.patch = Patch.current }

  has_and_belongs_to_many :dropped_by, class_name: 'Monster', before_add: :check_dropped_by
  has_and_belongs_to_many :sold_by, class_name: 'Npc', before_add: :check_sold_by
  has_and_belongs_to_many :images
  has_one :starts_quest, class_name: 'Quest', inverse_of: :dropped_as
  has_many :quest_rewards
  has_many :rewarded_from_quests, through: :quest_rewards, source: :quest
  has_many :quest_objectives
  has_many :required_for_quests, through: :quest_objectives, source: :quest

  META_CATEGORIES = {
    'armor' => %w[cloth_armor leather_armor chain_armor plate_armor].freeze,
    'weapon' => %w[club_weapon_1h dagger_weapon_1h fist_weapon_1h sword_weapon_1h
                   polearm_2h bo_staff_2h quarter_staff_2h].freeze
  }.freeze
  CATEGORIES = %w[general schematic container clickie scroll
                  potion ingredient food drink
                  shield held jewellery relic
                  catalyst component material reagent resource]
               .concat(META_CATEGORIES.values.flatten)
               .freeze
  CATEGORIES_CAMEL = CATEGORIES.map { |w| w.camelize(:lower) }

  # this should be in the view layer really. this is top-left of previews
  READABLE_CATEGORIES = CATEGORIES.map { |c| [c, c.titleize] }.to_h.tap do |c|
    c['club_weapon_1h'] = 'One-Handed Club'
    c['dagger_weapon_1h'] = 'One-Handed Dagger'
    c['fist_weapon_1h'] = 'One-Handed Fist Weapon'
    c['sword_weapon_1h'] = 'One-Handed Sword'
    c['polearm_2h'] = 'Two-Handed Polearm'
    c['bo_staff_2h'] = 'Two-Handed Bo Staff'
    c['quarter_staff_2h'] = 'Two-Handed Quarter Staff'

    c['cloth_armor'] = 'Cloth'
    c['leather_armor'] = 'Leather'
    c['chain_armor'] = 'Chain'
    c['plate_armor'] = 'Plate'
  end.freeze

  READABLE_SUBCATEGORIES = {
    'club_weapon_1h' => 'Crushing Weapon',
    'fist_weapon_1h' => 'Hand-to-Hand Weapon',
    'dagger_weapon_1h' => 'Dagger Weapon',
    'sword_weapon_1h' => 'Blade Weapon',
    'polearm_2h' => 'Spear Weapon',
    'bo_staff_2h' => 'Stave Weapon',
    'quarter_staff_2h' => 'Stave Weapon'
  }.freeze

  CATEGORIES_FOR_SELECT = READABLE_CATEGORIES.invert.to_a.sort.freeze

  SLOTS = %w[head shoulders hands back chest waist legs feet ears
             fingers neck relic onehanded twohanded offhand ranged].freeze
  SLOTS_CAMEL = SLOTS.map { |w| w.camelize(:lower) }

  ATTRS = %w[no_trade lifebound magic quest_item temporary unique].freeze
  ATTRS_CAMEL = ATTRS.map { |w| w.camelize(:lower) }

  # no need to camel this yet as no underscores
  CLASSES = %w[bard cleric direlord druid enchanter monk necromancer paladin
               ranger rogue shaman summoner warrior wizard].freeze

  STATS = %w[damage attack_power hit_rating
             spell_power spell_crit_chance
             health mana armor
             block_rating dodge parry
             haste_percent delay
             endurance
             health_recovery_while_resting mana_recovery_while_resting
             fire_resist cold_resist poison_resist chemical_resist nature_resist
             magic_resist shock_resist
             strength stamina constitution agility dexterity intellect wisdom charisma].freeze
  STATS_CAMEL = STATS.map { |w| w.camelize(:lower) }

  validates :name, presence: true, uniqueness: true
  validates :weight, presence: true

  validates :attrs, allow_blank: true, inclusion: { in: ATTRS }
  validates :category, presence: true, inclusion: { in: CATEGORIES }
  validates :classes, allow_blank: true, inclusion: { in: CLASSES }
  validates :slot, allow_blank: true, inclusion: { in: SLOTS }

  validate :stat_hash_valid

  # Should move to a global module
  def self.stats_type(stat)
    case stat.to_s
    when 'delay' then ::Float
    else ::Integer
    end
  end

  # Support for Administrate gem saving JSONB as a string
  def classes=(value)
    self[:classes] = value.is_a?(String) ? JSON.parse(value) : value
    self[:classes] = [] if classes.nil?
  end

  # Support for Administrate gem saving JSONB as a string
  def attrs=(value)
    self[:attrs] = value.is_a?(String) ? JSON.parse(value) : value
    self[:attrs] = [] if attrs.nil?
  end

  # Support for Administrate gem saving JSONB as a string
  def stats=(value)
    self[:stats] = value.is_a?(String) ? JSON.parse(value) : value
    self[:stats] = {} if stats.nil?

    self[:stats] = stats.map do |k, v|
      # iterate through and convert Strings to native values (from form submits)
      # need to merge this logic with stats_type
      v = k == 'delay' ? v.to_f : v.to_i

      # also remove zeroes
      next if v.zero?

      [k, v]
    end.compact.to_h
  end

  def weapon?
    category.in?(META_CATEGORIES['weapon'])
  end

  def armor?
    category.in?(META_CATEGORIES['armor'])
  end

  def general_stats
    stats.sort.reject do |k, _v|
      %w[damage delay armor].include?(k)
    end
  end

  def available_stats
    Item::STATS - stats.keys
  end

  private

  def stat_hash_valid
    unless stats.is_a?(Hash)
      errors.add(:stats, 'must be a hash')
      return
    end

    stats.each_key do |k|
      if STATS.include?(k)
        # removed for now, HTML form submits are strings
        # errors.add(:stats, "#{k}=#{v} is invalid, use numbers only") unless v.is_a?(Numeric) || v.nil?
      else
        errors.add(:stats, "#{k} is not a valid stats key")
      end
    end
  end

  def check_dropped_by(monster)
    return unless dropped_by.include?(monster)

    errors.add :base, 'already dropped by this monster'
    raise ActiveRecord::Rollback
  end

  def check_sold_by(npc)
    return unless sold_by.include?(npc)

    errors.add :base, 'already sold by this npc'
    raise ActiveRecord::Rollback
  end
end

app/controllers/admin/items_controller.rb
# frozen_string_literal: true

module Admin
  class ItemsController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes(action_name)).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-demo.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/api/v1/items_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class ItemsController < ApiController
      rescue_from ItemSearch::InvalidOperator do
        render json: { error: 'invalid operator' }
      end

      def search
        params = search_params.to_hash.sort.to_h.deep_symbolize_keys
        fingerprint = Digest::MD5.hexdigest(params.to_s)
        json = Rails.cache.fetch("items-search-#{fingerprint}", expires_in: 5.minutes) do
          items = ItemSearch.new(**params).search.all
          blueprint(items)
        end

        render json:
      end

      def index
        # experimenting with very short term caching
        json = Rails.cache.fetch('items', expires_in: 5.seconds) do
          items = Item.all
          blueprint(items)
        end

        render json:
      end

      def show
        render json: blueprint(item)
      end

      def create
        item = Item.new(item_params)
        if item.save
          Rails.cache.clear
          render json: blueprint(item)
        else
          render json: { errors: item.errors }
        end
      end

      def update
        if item.update(item_params)
          Rails.cache.clear
          render json: blueprint(item)
        else
          render json: { errors: item.errors }
        end
      end

      def destroy
        item = Item.find(params[:id])
        item.discard
        head 204
      end

      def assign
        # assign an item_id to a monster_id
        monster = Monster.find(params[:monster_id])
        item.dropped_by << monster unless item.dropped_by.include?(monster)

        head 204
      end

      def unassign
        # remove an item_id from a monster_id
        monster = Monster.find(params[:monster_id])
        item.dropped_by -= [monster]

        head 204
      end

      private

      def item
        @item ||= Item.find(params[:id])
      end

      def blueprint(item)
        ItemBlueprint.render(item, view: :full)
      end

      def item_params
        params.permit(:reward_from_quest_id, :name, :category, :weight, :slot,
                      :buy_price, :sell_price,
                      :required_level,
                      classes: [], attrs: [], stats: {})
      end

      def search_params
        params.permit(
          :name, :category, :class, :slot,
          :starts_quest, :reward_from_quest, :dropped_by,
          attrs: [],
          weight: %i[operator value],
          required_level: %i[operator value],
          stats: %i[stat operator value]
        )
      end
    end
  end
end

app/controllers/items_controller.rb
# frozen_string_literal: true

class ItemsController < ApplicationController
  before_action :item, only: %i[show]

  def search
    service = ItemSearch.new(name: params[:name])
    @items = service.search.includes(:dropped_by).order(:name)
    render partial: 'items/list'
  end

  def new
    @item = Item.new
  end

  def index
    @items = items
  end

  def show; end

  def edit
    head 403 unless can? :edit, item
  end

  def create
    head 403 unless can? :create, Item

    @item = Item.new

    if update_item
      redirect_to edit_item_path(item), notice: 'Changes Saved!'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    return head 403 unless can? :edit, item

    if update_item
      redirect_to edit_item_path(item), notice: 'Changes Saved!'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def dynamic_stats
    item = Item.new(item_params)
    item.stats.delete(params[:remove_stat]) if params[:remove_stat]
    add_stat = params[:add_stat] if params[:add_stat].present?

    render partial: 'items/dynamic_stats_form', locals: { item:, add_stat: }
  end

  private

  def items
    # TODO: work out why this includes isn't automatic
    Item.order(:name).includes(:dropped_by)
  end

  def item
    @item ||= Item.find(params[:id])
  end

  def update_item
    item.attrs = toggler_params(params[:attrs])
    item.classes = toggler_params(params[:classes])
    item.update(item_params)
  end

  def item_params
    params.require(:item).permit(:id, :name, :category, :weight,
                                 :required_level, :slot,
                                 :sell_price, :buy_price,
                                 :description, :public_notes, :private_notes,
                                 stats: {})
  end

  def toggler_params(prm)
    prm.to_unsafe_h.map do |attr, v|
      v == 'true' ? attr : nil
    end.compact
  end
end

app/views/items/_button_toggler.html.slim
div.button-toggler data-controller="button-toggler" data-button-toggler-on-class='has-text-weight-bold is-success' data-button-toggler-off-class='is-light is-danger' data-button-toggler-slug-value=slug
  input data-button-toggler-target="input" type="hidden" name=name value="#{enabled}"
  // classes set by button-toggler js
  button.button.is-fullwidth type="button" data-button-toggler-target="button" data-action="button-toggler#toggle"
    = label

app/views/items/_dynamic_stats_form.html.slim
= turbo_frame_tag 'dynamicStatsFrame', 'data-dynamic-stats-target': 'turboFrame'
  .columns.is-multiline.is-mobile
    // use category to always render certain fields
    - if item.weapon?
      - rendered_stats = %w[damage delay]
      = render partial: 'stat_item', locals: { k: 'damage', v: item.stats['damage'], removable: false }
      = render partial: 'stat_item', locals: { k: 'delay', v: item.stats['delay'], removable: false }

    - if item.armor?
      - rendered_stats = %w[armor]
      = render partial: 'stat_item', locals: { k: 'armor', v: item.stats['armor'], removable: false }

    // populated stats, minus any we did above.
    // also remove empty keys which does two things: if category changes to weapon then
    // back out, it removes the empty damage+delay we added.
    // and also if "add item" is clicked multiple times,
    // only the most recent one stays (previous ones are empty and thus removed here)
    - stats = item.stats.except(*rendered_stats).select{|k, v| v.present? }.keys

    // any manually added stat; note stats is now an array of slugs
    - stats << add_stat if defined?(add_stat) && add_stat.present?
    - stats.sort.each do |k|
      = render partial: 'stat_item', locals: { k:, v: item.stats[k], removable: true }

    .column.is-3-mobile.is-2-tablet
      label.label Add Stat..
      .field
        .control
          .select.is-fullwidth
            = select_tag 'add_stat', options_for_select(Item::STATS - Array(rendered_stats) - stats), include_blank: '', data: { action: 'change->dynamic-stats#add_stat', 'dynamic-stats-target': 'addStat' }

app/views/items/_form.html.slim
// TODO..
//  slot - only show for certain categories (new stimulus controller? where is the src?)

.section data-controller='dynamic-stats' data-dynamic-stats-url-value=dynamic_stats_items_path
  .container
    h1.title
      = @item.name
      - if @item.persisted?
        '
        a href=item_path(@item) [back]

    = render partial: 'partials/message' if flash.notice

    = render partial: 'partials/form_error_messages', locals: { object: @item }

    = form_for @item, html: { 'data-dynamic-stats-target': 'form' }, multipart: true do |f|
      .columns
        .column
          .field
            label.label
              span Name
              span class="has-text-danger" *
            .control
              = f.text_field :name, class: 'input is-medium'

        .column.is-3
          .field
            label.label
              span Category
              span class="has-text-danger" *
            .control
              .select.is-fullwidth.is-medium
                = f.select :category, options_for_select(Item::CATEGORIES_FOR_SELECT, @item.category), {}, 'data-action': 'change->dynamic-stats#change_category'

        .column.is-1
          .field
            label.label
              span Weight
              span class="has-text-danger" *
            .control
              = f.text_field :weight, class: 'input is-medium'

      = render partial: 'items/dynamic_stats_form', locals: { item: @item }

      .columns
        .column.is-8 data-controller="item-class-setter" data-item-class-setter-button-toggler-outlet=".button-toggler"
          label.label
            span Classes
            span<
              | [tanks:
            a< data-arg="tanks" data-action="item-class-setter#on" on
            a< data-arg="tanks" data-action="item-class-setter#off" off
            span< heals:
            a< data-arg="heals" data-action="item-class-setter#on" on
            a< data-arg="heals" data-action="item-class-setter#off" off
            span< casts:
            a< data-arg="casts" data-action="item-class-setter#on" on
            a< data-arg="casts" data-action="item-class-setter#off" off
            span< dps:
            a< data-arg="dps" data-action="item-class-setter#on" on
            a< data-arg="dps" data-action="item-class-setter#off" off
            span< support:
            a< data-arg="support" data-action="item-class-setter#on" on
            a< data-arg="support" data-action="item-class-setter#off" off
            span
              | ]
          .columns.is-multiline.is-mobile.classes
            - Item::CLASSES.each do |kls_slug|
              .column.is-one-fifth-tablet.is-half-mobile
                = render partial: 'button_toggler', locals: { enabled: @item.classes.include?(kls_slug), name: "classes[#{kls_slug}]", label: kls_slug.titleize, slug: kls_slug }

        .column.is-4
          .field
            label.label Attributes
            .columns.is-multiline.is-mobile
              - Item::ATTRS.each do |attr|
                .column.is-4-tablet.is-half-mobile
                  = render partial: 'button_toggler', locals: { enabled: @item.attrs.include?(attr), name: "attrs[#{attr}]", label: attr.titleize, slug: attr }



      .columns
        .column.is-2
          .field
            label.label Req Level
            .control
              = f.number_field :required_level, min: 1, max: 50, class: 'input'
        .column.is-2
          .field
            label.label Slot
            .control
              .select.is-fullwidth
                = f.select :slot, options_for_select(Item::SLOTS, @item.slot), include_blank: ''
        .column data-controller="copper-to-pgsc"
          = render partial: 'partials/pgsc', locals: { label: 'Sell Price', name: 'item[sell_price]', value: @item.sell_price }
        .column data-controller="copper-to-pgsc"
          = render partial: 'partials/pgsc', locals: { label: 'Buy Price', name: 'item[buy_price]', value: @item.buy_price }


      .columns
        .column
          .field
            label.label Description
            .control
              = f.text_area :description, class: 'textarea'


        .column
          .field
            label.label Public Notes
            .control
              = f.text_area :public_notes, class: 'textarea'

        .column
          .field
            label.label Private Notes
            .control
              = f.text_area :private_notes, class: 'textarea'

      .columns
        .column
          .field.is-grouped
            .control
              button class="button is-link" type="submit" Save
            .control
              - if @item.persisted?
                a class="button is-danger" href=item_path(@item) Cancel
              - else
                a class="button is-danger" href=items_path Cancel

        .column
          div style="margin-left: auto"
            = render partial: 'preview', locals: { item: @item }

app/views/items/_list.html.slim
= turbo_frame_tag 'itemList'
  table.table
    thead
      tr
        th Name
        th Category
        th Drop
        - if can? :edit, Item
          th

    tbody
      - @items.each do |item|
        tr
          td
            - if can? :read, item
              a data-turbo-frame="_top" href=item_path(item)
                = item.name
            - else
              = item.name

          td
            = Item::READABLE_CATEGORIES[item.category]

          td
            - if drop = item.dropped_by.first
              a data-turbo-frame="_top" href=monster_path(drop)
                = drop.name

          - if can? :edit, item
            td
              a data-turbo-frame="_top" href=edit_item_path(item) edit

app/views/items/_preview.html.slim
.item-screenshot
  .columns.is-mobile.is-gapless.mb-0
    .column
      .name.is-size-5 = item.name
    .column.has-text-right
      .attrs
        = item.attrs.map(&:titleize).join(', ')
  .body
    - if item.weapon?
      .columns.is-mobile.is-gapless.mb-0
        .column
          div= Item::READABLE_CATEGORIES[item.category]
          div= "#{item.stats['damage']} Physical damage"
        .column.has-text-right
          div= Item::READABLE_SUBCATEGORIES[item.category]
          div= "#{item.stats['delay']} Delay"

    - elsif item.armor?
      .columns.is-mobile.is-gapless.mb-0
        .column
          div= Item::READABLE_CATEGORIES[item.category]
          - if item.stats['armor']
            div= "#{item.stats['armor']} Armor"
        .column.has-text-right
          div= item.slot&.titleize

    - elsif item.category == 'shield'
      .columns.is-mobile.is-gapless.mb-0
        .column
          div= Item::READABLE_CATEGORIES[item.category]
          - if item.stats['armor']
            div= "#{item.stats['armor']} Armor"

    - item.general_stats.each do |k, v|
      div
        = "#{v} #{k.titleize}"

    - if item.classes.any?
      div
        = "Class: "
        = item.classes.map(&:titleize).join(', ')


    - if item.required_level
      div = "Requires Level #{item.required_level}"


    - if item.description
      .description = item.description

    .weight.has-text-right Weight: #{item.weight}

app/views/items/_search.html.slim
= form_tag search_items_path, method: 'get', 'data-controller': 'realtime-search', 'data-turbo-frame': 'itemList'
  .columns
    .column
      .field
        label.label Search
        .control.has-icons-left
          input.input name="name" value=params[:name] type="text" placeholder="Search" data-action='realtime-search#search'
          span class='icon is-left'
            i class='fas fa-magnifying-glass'

app/views/items/_stat_item.html.slim
.column.is-3-mobile.is-2-tablet
  label.label = k.titleize
  .field class=('has-addons' if removable)
    .control
      input.input type="text" name="item[stats][#{k}]" value=v

    - if removable
      .control
        button.button type="button" data-dynamic-stats-remove-stat-key-param=k data-action="dynamic-stats#remove_stat"
          span.icon
            i.fas.fa-times

app/views/items/edit.html.slim
// TODO..
//  slot - only show for certain categories (new stimulus controller? where is the src?)
//  classes - row of small buttons?
//  attrs - row of small buttons?

.section data-controller='dynamic-stats' data-dynamic-stats-url-value=item_dynamic_stats_path(@item)
  .container
    h1.title
      = @item.name
      '
      a href=item_path(@item) [back]

    = render partial: 'partials/message' if flash.notice

    = render partial: 'partials/form_error_messages', locals: { object: @item }

    = form_for @item, html: { 'data-dynamic-stats-target': 'form' }, multipart: true do |f|
      .columns
        .column
          .field
            label.label
              span Name
              span class="has-text-danger" *
            .control
              = f.text_field :name, class: 'input is-medium'

        .column.is-3
          .field
            label.label
              span Category
              span class="has-text-danger" *
            .control
              .select.is-fullwidth.is-medium
                = f.select :category, options_for_select(Item::CATEGORIES_FOR_SELECT, @item.category), {}, 'data-action': 'change->dynamic-stats#change_category'

        .column.is-1
          .field
            label.label
              span Weight
              span class="has-text-danger" *
            .control
              = f.text_field :weight, class: 'input is-medium'

      .columns
        .column.is-2
          .field
            label.label Req Level
            .control
              = f.number_field :required_level, min: 1, max: 50, class: 'input'
        .column.is-2
          .field
            label.label Slot
            .control
              .select.is-fullwidth
                = f.select :slot, options_for_select(Item::SLOTS, @item.slot), include_blank: ''
        .column data-controller="copper-to-pgsc"
          = render partial: 'partials/pgsc', locals: { label: 'Sell Price', name: 'item[sell_price]', value: @item.sell_price }
        .column data-controller="copper-to-pgsc"
          = render partial: 'partials/pgsc', locals: { label: 'Buy Price', name: 'item[buy_price]', value: @item.buy_price }

      .columns
        .column.is-8
          .field
            label.label Classes
            .columns.is-multiline.is-mobile
              - Item::CLASSES.each do |kls_slug|
                .column.is-one-fifth-tablet.is-half-mobile
                  = render partial: 'button_toggler', locals: { enabled: @item.classes.include?(kls_slug), name: "classes[#{kls_slug}]", label: kls_slug.titleize }

        .column.is-4
          .field
            label.label Attributes
            .columns.is-multiline.is-mobile
              - Item::ATTRS.each do |attr|
                .column.is-4-tablet.is-half-mobile
                  = render partial: 'button_toggler', locals: { enabled: @item.attrs.include?(attr), name: "attrs[#{attr}]", label: attr.titleize }


      = render partial: 'items/dynamic_stats_form', locals: { item: @item }


      .columns
        .column
          .field
            label.label Public Notes
            .control
              = f.text_area :public_notes, class: 'textarea'

        .column
          .field
            label.label Private Notes
            .control
              = f.text_area :private_notes, class: 'textarea'

      .columns
        .column
          .field.is-grouped
            .control
              button class="button is-link" type="submit" Save
            .control
              a class="button is-danger" href=item_path(@item) Cancel

        .column
          div style="margin-left: auto"
            = render partial: 'preview', locals: { item: @item }

app/views/items/index.html.slim
= turbo_frame_tag 'itemSearchForm'
  .section
    .container
      .block = render partial: 'search'

      = render partial: 'items/list'

app/views/items/new.html.slim
= render partial: 'form'

app/views/items/show.html.slim
.section
  .container
    .columns
      .column
        h1.title
          = @item.name
          - if can? :edit, @item
            '
            a href=edit_item_path(@item) [edit]


        .field.is-grouped
          .control
            .tags.has-addons
              span.tag.is-dark.is-medium Category
              span.tag.is-success.is-medium = @item.category.titleize

          - if @item.weight
            .control
              .tags.has-addons
                span.tag.is-dark.is-medium Weight
                span.tag.is-success.is-medium = "#{@item.weight}kg"


          - @item.attrs.sort.each do |attr|
           .control
              span.tag.is-info.is-medium = attr.titleize


        table.table
          thead
            tr
              th Stat
              th

          tbody
            - @item.stats.sort.each do |k, v|
              tr
                td = k.titleize
                td.has-text-right = v

      .column.is-6
        = render partial: 'preview', locals: { item: @item }